InstaClone/InstaClone/Controllers/PhotoController.cs
using InstaClone.Data;
using InstaClone.Models;
using InstaClone.Models.Photo;
using InstaClone.Models.Profile;
using InstaClone.Models.User;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace InstaClone.Controllers
{
    public class PhotoController:Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly ApplicationDbContext _context;
        private readonly IPhoto _photoService;

        public PhotoController(IHostingEnvironment hostingEnvironment, ApplicationDbContext context, IPhoto photoService) 
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
            _photoService = photoService;
        }

        public IActionResult Upload() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult UploadPhoto(PhotoViewModel model) 
        {
            string uniqueFileName = null;
            if (model.Photo != null)
            {
                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
            }

            var photo = new PhotoModel
            {
                Photo = uniqueFileName,
                Name = model.UserName
            };

            _context.Photos.Add(photo);
            _context.SaveChanges();

            return RedirectToAction("Index","Home");
        }

        public async Task<IActionResult> Delete(int id) 
        {
            await _photoService.Delete(id);
            return RedirectToAction("Index", "Home");
        }

    }
}

InstaClone/InstaClone/Controllers/ProfileController.cs
using InstaClone.Data;
using InstaClone.Models;
using InstaClone.Models.Profile;
using InstaClone.Models.User;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace InstaClone.Controllers
{
    public class ProfileController:Controller
    {
        private readonly IApplicationUser _userService;
        private readonly ApplicationDbContext _context;
        public ProfileController(IApplicationUser userService, ApplicationDbContext context) 
        {
            _userService = userService;
            _context = context;
        }
        public IActionResult Detail(string id)
        {
            var user = _userService.GetById(id);
            var model = new ProfileModel
            {
                Name = user.UserName,
                Image = user.Image,
                Id = user.Id
            };

            return View(model) ;
        }


    }
}

InstaClone/InstaClone/Controllers/SearchController.cs
using InstaClone.Data;
using InstaClone.Models.Profile;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InstaClone.Controllers
{
    public class SearchController:Controller
    {
        private readonly IApplicationUser _userService;
        public SearchController(IApplicationUser userService) 
        {
            _userService = userService;
        }

        public IActionResult Index(SearchIndexModel model) 
        {
            var users = _userService.GetFilteredUsers(model.QueryString);
            var noResult = (!string.IsNullOrEmpty(model.QueryString) && (!users.Any()));
        
            var model1 = new SearchIndexModel
            {
                QueryString = model.QueryString,
                QueryResult = users,
                IsNoResult = noResult
            };

            return View(model1);
        }

        [HttpPost]
        public IActionResult Search(SearchIndexModel model)
        {
            return RedirectToAction("Index", new { model.QueryString });
        }

        public IActionResult UserProfile(string name) 
        {
            var user = _userService.GetAllUsers().FirstOrDefault(u => u.UserName == name);

            var model = new ProfileModel
            {
                Name = user.UserName,
                Image = user.Image
            };

            return View(model);
        }

    }
}

InstaClone/InstaClone/Views/Search/Index.cshtml
@model InstaClone.Models.Profile.SearchIndexModel
@inject ApplicationDbContext DbContext

<div>
    @if (Model.QueryString != null)
    {
        @foreach (var m in Model.QueryResult)
        {
            <h2><a asp-controller="Search" asp-action="UserProfile" asp-route-name="@m.UserName">@m.UserName</a></h2>
        }
    }

</div>

@if (Model.IsNoResult)
{
    <div>
        <h2>No Users</h2>
    </div>
}

InstaClone/InstaClone/Views/Search/UserProfile.cshtml
@model InstaClone.Models.Profile.ProfileModel
@inject ApplicationDbContext DbContext

@{
    var photoPath = "~/images/" + (Model.Image ?? "noimage.jpg");
    ViewData["Title"] = Model.Name + " Profile";
}

    <div class="card">
        <div class="card-header">
            <h2>@Model.Name</h2>
            <a asp-controller="Profile" asp-action="Follow" asp-route-name="@Model.Name" class="btn btn-primary">Follow</a>

            <!--Need to be removed-->
            @if (User.Identity.Name == Model.Name)
            {
                <div class="uploadBtn">
                    <a asp-controller="Photo" asp-action="Upload" class="btn btn-dark">Upload</a>
                </div>
            }

        </div>
        <div class="card-body">
            <img class="card-img-top userProfilePhoto" src="@photoPath" asp-append-version="true" />
        </div>
        <div class="card-footer">
            @foreach (var m in DbContext.Photos)
            {
                if (m.Name == Model.Name)
                {
                    var photoPath2 = "~/images/" + (m.Photo ?? "noimage.jpg");
                    <img class="card-img-top userAllPhotos" src="@photoPath2" asp-append-version="true" />  
                }
            }
        </div>
    </div>